### ISSUE TITLE
[BUG]: Navigation Bar Doesn't Adjust Responsively on Smaller Screens

### ISSUE THREAD

**Issue by vine16** [electron/website#538] opened 2024-03-23 16:34 UTC
- **Problem**: Several div elements within the navigation bar collapse and overlap on screens smaller than a standard PC display.
- **Late Addition to Hamburger Menu**: Divs are added to the hamburger menu on the page, but this process occurs very late in the resizing, suggesting that breakpoints for responsiveness should be adjusted to trigger earlier.
- **Impact**: This issue affects the usability and visual presentation of the website, particularly on devices with limited screen real estate.
- **Importance of Resolution**: It is crucial to address this problem promptly to ensure a seamless and responsive user experience across various devices and screen sizes.
![image](https://github.com/electron/website/assets/83833234/c9157d4b-efbd-4c6a-8eae-e71054417958)

**Comment by erickzhao** [comment] 2024-03-25 21:12
Duplicate of #369

**Closed by erickzhao** 2024-03-25 21:12 UTC
